import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home(props:any) {
  console.log(props)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>{props.now}</div>

    </div>
  )
}
export async function getStaticProps() { //服务端调用的方法
  const now = new Date().toLocaleTimeString();
  const res = await fetch(`https://postman-echo.com/get?now=${now}`);
  const obj = await res.json();
  return {
    props: {
      now: obj.args.now,
    },
  };
}
